name: Testing Cross-compilation

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Install devbox dependencies
        run: devbox install

      - name: Install nix-darwin
      - run: devbox run darwin-install

      - name: Switch as m2pro
      - run: devbox run m2pro

      - name: Build Nixos for rpi4
        run: devbox run rpi4
